In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [6]:
indep = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [7]:
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dep = dataset[['charges']]

In [9]:
dep

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [ ]:
# split into train set and test set

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(indep,dep,test_size=1/3,random_state=0)
print("x_train:", x_train.shape)
print("x_test :", x_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

x_train: (892, 5)
x_test : (446, 5)
y_train: (892, 1)
y_test : (446, 1)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
param_grid = {
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'max_depth': [None, 3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

grid_search = GridSearchCV(
   RandomForestRegressor(),
    param_grid,
    refit=True,
    n_jobs=-1,
    verbose=1
)

grid_search.fit(x_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best R2 Score:", grid_search.best_score_)

Fitting 5 folds for each of 135 candidates, totalling 675 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Best Parameters: {'criterion': 'absolute_error', 'max_depth': 7, 'min_samples_leaf': 4, 'min_samples_split': 10}
Best R2 Score: 0.8350528740790629

In [15]:
# print best parameter after tuning
re = grid_search.cv_results_
print ("r_score value best parameter {}:".format(grid_search.best_params_))

r_score value best parameter {'criterion': 'absolute_error', 'max_depth': 7, 'min_samples_leaf': 4, 'min_samples_split': 10}:

In [16]:
table = pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.296282,0.008703,0.020558,0.000588,squared_error,None,1,2,"{'criterion': 'squared_error', 'max_depth': No...",0.802512,0.749347,0.837955,0.807343,0.766696,0.792771,0.031351,133
1,0.251791,0.009062,0.017512,0.001811,squared_error,None,1,5,"{'criterion': 'squared_error', 'max_depth': No...",0.812857,0.769068,0.847850,0.812575,0.773853,0.803241,0.028986,127
2,0.229482,0.036446,0.017529,0.000574,squared_error,None,1,10,"{'criterion': 'squared_error', 'max_depth': No...",0.819906,0.780762,0.855987,0.830220,0.782759,0.813927,0.028781,119
3,0.224798,0.007127,0.017829,0.002074,squared_error,None,2,2,"{'criterion': 'squared_error', 'max_depth': No...",0.818414,0.779944,0.841946,0.836624,0.781477,0.811681,0.026469,122
4,0.216424,0.012297,0.017523,0.001894,squared_error,None,2,5,"{'criterion': 'squared_error', 'max_depth': No...",0.817387,0.785104,0.848730,0.841666,0.783676,0.815313,0.027309,113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,0.360836,0.116105,0.018575,0.002111,poisson,10,2,5,"{'criterion': 'poisson', 'max_depth': 10, 'min...",0.817657,0.787341,0.846828,0.846651,0.783686,0.816432,0.027412,110
131,0.281818,0.077819,0.016710,0.000417,poisson,10,2,10,"{'criterion': 'poisson', 'max_depth': 10, 'min...",0.824863,0.801970,0.855508,0.852100,0.786861,0.824260,0.027009,81
132,0.338096,0.125886,0.017818,0.002691,poisson,10,4,2,"{'criterion': 'poisson', 'max_depth': 10, 'min...",0.821217,0.802957,0.854182,0.853596,0.792404,0.824871,0.025424,75
133,0.290722,0.071916,0.021986,0.010801,poisson,10,4,5,"{'criterion': 'poisson', 'max_depth': 10, 'min...",0.823245,0.801591,0.854448,0.851818,0.791860,0.824593,0.025436,76
134,0.239313,0.044050,0.016780,0.001348,poisson,10,4,10,"{'criterion': 'poisson', 'max_depth': 10, 'min...",0.823931,0.808656,0.858153,0.855959,0.793180,0.827976,0.025667,53

In [18]:
age_input = float(input("Age:"))
bmi_input = float(input("BMI:"))
children_input = float(input("Children:"))
sex_male_input = int(input("Sex male 0 or 1:"))
smoker_yes_input = int(input("smoker yes 0 or 1:"))

Age: 27
BMI: 30
Children: 0
Sex male 0 or 1: 1
smoker yes 0 or 1: 0

In [19]:
Future_Prediction = grid_search.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_Prediction))

Future_prediction=[18111.23138335]